micromatch/picomatch

lib/utils.js

I noticed in another PR to micromatch that some tests were failing because node `12.2.0` would cause the `utils.supportsLookbehinds` method to return `false`.
- only check minor when major is version 8
- all majors greater than or equal to 9 support lookbehinds

supports lookbehinds

---

README.md

It wasn't properly displayed as a table

Fix "Extglobs" table in readme

---

.eslintrc.json

Based on the discussion from #30
Adding rule to catch incorrect spacing in object -`{noext: true }`

Add eslint object-curly-spacing rule

---

package.json

This fixes the npm audit vulnerabilities.

Update mocha to v6.2.2 and nyc to v14.1.1.

---

.verb.md
README.md

BTW bugs everywhere :P `verb` is using backslashes on Windows leading to broken links :)
PS. this will conflict with #37, but I will rebase if needed.

Doc: minor typo fixes and Markdown tweaks

---

.eslintignore
.eslintrc.json
bench/first-match-minimatch.js
bench/first-match-picomatch.js
bench/load-time.js
examples/extglob.js
test/.eslintrc.json

* add .eslintignore so that nested folders node_modules are ignored too
* remove unneeded parser options
* remove unneeded globals
* add strict
* move `mocha: true` to tests since that's where it's needed only
* enable a few other rules that the codebase already complies with
The strict addition in examples is also in #42, so one will need to be reabsed. Let me know if you want me to make any changes.
PS. IMO ESLint should be added to the devDependencies and add a script too, otherwise there's no consistency.

Tweak ESLint config

---

package.json

This brings test time down ~1s from ~15s on my Windows machine.
Linux might not see such a huge improvement, but it should still be faster.

Change mocha reporter to dot.

---

bench/index.js
lib/parse.js
lib/utils.js

Would be nice to have a benchmark before merging this :)
Also, if we go with this, we should eventually update the ESLint config to check for the modern features (`prefer-*` rules).

Use template literals.

---

.eslintignore
.eslintrc.json
package.json

Unfortunately, due to ESLint 6.x requiring Node.js >= 8.10, we need to stick with ESLint 5.x.

Add ESLint as a devDependency.

---

lib/picomatch.js
test/api.picomatch.js

This PR disables the `fastpaths` mode for the `parse` method. The main reason is that when the mode is enabled, no tokens are returned for the some patterns like `a*.txt`:
**Before**
```js
var picomatch = require("picomatch");
console.log(picomatch.parse('a*.txt').tokens);
// [Object {output: "", type: "bos", value: ""}]
```
**After**
```js
var picomatch = require("picomatch");
console.log(picomatch.parse('a*.txt', { fastpaths: false }).tokens);
// Array (4 items)
// 0: Object {output: "", type: "bos", value: ""}
// 1: Object {prev: Object {output: "", type: "bos", value: ""}, type: "text", value: "a"}
// 2: Object {output: "[^/]*?", …}
// 3: Object {output: "\\.", …}
// Array Prototype
```
The `parse` method must always return tokens, otherwise it makes no sense.

Disable fastpaths mode for the parse method

---

lib/parse.js

For some patterns the `.parse` method returns tokens with correct type but wrong value.
```js
// a/b/**/
[
[ 'bos', '' ],
[ 'text', 'a' ],
[ 'slash', '/' ],
[ 'text', 'b' ],
[ 'slash', '/' ],
[ 'globstar', '**' ],
[ 'slash', '*' ] // <------------- * — before, / — after
]
// **/a
[
[ 'bos', '' ],
[ 'globstar', '**' ],
[ 'slash', '*' ], // <------------ * — before, / — after
[ 'text', 'a' ]
]
```
I don't know where I must write tests for it :)

Do not use previous value for the slash token

---

lib/picomatch.js

I noticed that the code coverage decreased with #51. This PR uses the `parse` function directly internally, which increases code coverage.

use parse function directly

---

lib/scan.js
test/api.scan.js

This is a partial fix of #58. Source for this case is https://github.com/mrmlnc/fast-glob/issues/263.
Changes:
* Add some tests for the `scan` method; I tried to collect all the edge cases.
* Correctly handle a case with a part after parentheses. E.g. `base/(a|b)/*.js`
I'm not sure how to test this correctly. Changes based on `extglob` support:
https://github.com/micromatch/picomatch/blob/66e1b200f3ea1784bdeae0770c8e5cd95f55e334/lib/scan.js#L169-L199.

ISSUE-58: Correctly handle a part after parentheses

---

README.md

Not sure if this is worth a PR, but the backtick is not a special character in `picomatch` nor regular regex and attempting to escape it is going to cause some problems.

Special character typo in readme

---

lib/parse.js
test/api.picomatch.js

This way micromatch can detect that this is a negation pattern.
Fixes micromatch/micromatch#179

fix: set negatedExtGlob also if it does not span the whole pattern

---

lib/scan.js
test/api.scan.js

This allows consumers to see if the glob starts with a negated extglob similar to parse.
At first I wondered if this should maybe set negated to true, but that might be a breaking change and also is then completely different from parse.
One example is jest which uses `scan` and `matcher` to mimic micromatchs main api. https://github.com/facebook/jest/blob/d49cb30fb2540efa8c451fb6cb24e8997284bc67/packages/jest-util/src/globsToMatcher.ts#L49-L52
This makes it possible to solve this issue micromatch/micromatch#179 in jest as well as basically support all negated extglobs as non of them work correctly atm.

feat: Add new `negatedExtglob` state to result of scan

---

lib/parse.js
test/extglobs.js

This is a fix for #93.
Please read the comment in the code. More context of the suggested solution is [here](https://github.com/micromatch/picomatch/issues/93#issuecomment-1003734593).

ISSUE-93: support stars in negation extglobs with expression after closing parenthesis

---

lib/parse.js
lib/utils.js
test/regex-features.js

In order to support more JS runtimes besides Node.js, this PR drops the check for `process` global.
The `process` global was only used to improve the error message for Node.js less than 10 (released April 2018).
This could be considered a breaking change since the error message will change, however this package already specifies package.json `engines.node` with `>=10`, so perhaps no one can even run it on older versions of Node.js without an install error.
https://github.com/micromatch/picomatch/blob/5214db489eb118db1bcfde39f446188757bb45cf/package.json#L20
- Related to https://github.com/micromatch/picomatch/issues/123

feat!: remove process global to work outside of node

---

lib/parse.js
test/api.picomatch.js

Previously sibling `text` tokens would exclude the `output` from the first token, resulting in the referenced issues. I think this should be a fairly safe change.
Fixes #125
Fixes #100

fix bad `text` values in `parse`

---

index.js

compatible browser environment, see https://github.com/micromatch/picomatch/issues/123

feat: compatible browser environment
